CREATE TABLE IF NOT EXISTS research_readiness_runs (
    research_run_id VARCHAR PRIMARY KEY,
    research_key VARCHAR NOT NULL,
    readiness_policy_version VARCHAR NOT NULL,
    validation_policy_version VARCHAR NOT NULL,
    trigger_kind VARCHAR NOT NULL,
    checked_at TIMESTAMPTZ NOT NULL,
    status VARCHAR NOT NULL,
    dataset_fingerprint VARCHAR NOT NULL,
    evaluation_fingerprint VARCHAR,
    decision_horizon_hours BIGINT NOT NULL,
    min_train_size BIGINT NOT NULL,
    test_size BIGINT NOT NULL,
    calibration_size BIGINT NOT NULL,
    bootstrap_iterations BIGINT NOT NULL,
    candidate_event_count BIGINT NOT NULL,
    decisive_event_count BIGINT NOT NULL,
    usable_sample_count BIGINT NOT NULL,
    decision_odds_covered_count BIGINT NOT NULL,
    closing_odds_covered_count BIGINT NOT NULL,
    skipped_missing_odds BIGINT NOT NULL,
    skipped_non_decisive_result BIGINT NOT NULL,
    skipped_feature_error BIGINT NOT NULL,
    evaluation_min_usable_samples BIGINT NOT NULL,
    evaluation_sample_capacity BIGINT NOT NULL,
    validation_min_evaluation_samples BIGINT NOT NULL,
    validation_min_usable_samples BIGINT NOT NULL,
    remaining_to_evaluation BIGINT NOT NULL,
    remaining_to_validation_samples BIGINT NOT NULL,
    fold_count_capacity BIGINT NOT NULL,
    ready_for_evaluation BOOLEAN NOT NULL,
    validation_sample_ready BOOLEAN NOT NULL,
    blockers_json JSON NOT NULL,
    evaluation_sample_count BIGINT,
    validation_passed BOOLEAN,
    report_relative_path VARCHAR,
    model_promotion_performed BOOLEAN NOT NULL DEFAULT FALSE,
    error_summary VARCHAR
);

CREATE INDEX IF NOT EXISTS idx_research_readiness_key_checked
ON research_readiness_runs (research_key, checked_at);
